# Generated by Django 5.0.14 on 2025-12-24 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HeroBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.CharField(blank=True, max_length=255)),
                ("image", models.ImageField(upload_to="banners/")),
                (
                    "link_url",
                    models.CharField(
                        blank=True, help_text="Optional link URL", max_length=500
                    ),
                ),
                (
                    "button_text",
                    models.CharField(blank=True, default="Shop Now", max_length=50),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
